// Code generated by scripts/sync-embed. DO NOT EDIT.
//
// Embed copies below are regenerated from canonical sources so go:embed
// can reach them (patterns cannot leave this package). Sources:
//
//	herdr-plugin.toml     <- ../herdr-plugin.toml
//	logo.svg              <- ../docs/assets/logo.svg
//	workflow.schema.json  <- ../docs/workflow.schema.json
//	skills/**             <- ../skills/**
//
// Drift is gated by embed_test.go assertCopy and `go run ./scripts/sync-embed`.
package assets
