import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { encodePayload } from "../src/workflow/exchange";
import { parseRaw, referencedWorkflowChildren } from "../src/workflow/grammar";

const EXAMPLES_DIR = join(import.meta.dir, "..", "examples");
const OUT = join(import.meta.dir, "..", "docs", ".vitepress", "theme", "examples.generated.ts");

export type ExampleCard = {
  name: string;
  desc: string;
  body: string;
  payload: string;
};

export async function buildExamples(dir = EXAMPLES_DIR): Promise<ExampleCard[]> {
  const names = (await readdir(dir))
    .filter((f) => f.endsWith(".yaml"))
    .map((f) => f.replace(/\.yaml$/, ""))
    .sort();
  const sources = new Map(
    await Promise.all(
      names.map(async (name) => {
        const body = await readFile(join(dir, `${name}.yaml`), "utf8");
        return [name, { body, raw: parseRaw(`${name}.yaml`, body) }] as const;
      }),
    ),
  );
  const collect = (name: string, seen: Set<string>): void => {
    if (seen.has(name)) return;
    seen.add(name);
    const source = sources.get(name);
    if (!source) throw new Error(`example '${name}' references missing child workflow`);
    for (const child of referencedWorkflowChildren(source.raw)) collect(child, seen);
  };
  const cards: ExampleCard[] = [];
  for (const [name, source] of sources) {
    if (source.raw.hidden === true) continue;
    const bundle = new Set<string>();
    collect(name, bundle);
    cards.push({
      name,
      desc: source.raw.description ?? "",
      body: source.body,
      payload: encodePayload(
        [...bundle].map((entry) => ({ name: entry, yaml: sources.get(entry)!.body })),
      ),
    });
  }
  return cards;
}

export function renderModule(cards: ExampleCard[]): string {
  return `// Generated by scripts/generate-examples.ts from examples/ — do not edit.\nexport default ${JSON.stringify(cards, null, 2)} as const;\n`;
}

if (import.meta.main) {
  await writeFile(OUT, renderModule(await buildExamples()));
}
