import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { encodePayload } from "../src/workflow/payload";
import { parseRaw } from "../src/workflow/parse";

const EXAMPLES_DIR = join(import.meta.dir, "..", "examples");
const OUT = join(import.meta.dir, "..", "docs", ".vitepress", "theme", "examples.generated.ts");

export type ExampleCard = {
  name: string;
  desc: string;
  body: string;
  payload: string;
};

export async function buildExamples(dir = EXAMPLES_DIR): Promise<ExampleCard[]> {
  const names = (await readdir(dir))
    .filter((f) => f.endsWith(".yaml"))
    .map((f) => f.replace(/\.yaml$/, ""))
    .sort();
  const cards: ExampleCard[] = [];
  for (const name of names) {
    // Working-tree checkout may be CRLF under core.autocrlf; keep the gallery LF-stable.
    const body = (await readFile(join(dir, `${name}.yaml`), "utf8")).replace(/\r\n/g, "\n");
    const raw = parseRaw(`${name}.yaml`, body);
    cards.push({
      name,
      desc: raw.description ?? "",
      body,
      payload: encodePayload([{ name, yaml: body }]),
    });
  }
  return cards;
}

export function renderModule(cards: ExampleCard[]): string {
  return `// Generated by scripts/generate-examples.ts from examples/ — do not edit.\nexport default ${JSON.stringify(cards, null, 2)} as const;\n`;
}

if (import.meta.main) {
  await writeFile(OUT, renderModule(await buildExamples()));
}
